"""
Report Generator — produces a clean HTML report from scan results.
"""
from pathlib import Path
from datetime import datetime

SEVERITY_COLOR = {"CRITICAL": "#e74c3c", "HIGH": "#e67e22", "MEDIUM": "#f1c40f", "LOW": "#2ecc71"}

def generate_report(results: dict, output_dir: str) -> str:
    findings = results["findings"]
    meta     = results["metadata"]
    total    = len(findings)
    vulns    = [f for f in findings if f["status"] == "VULNERABLE"]
    by_sev   = {}
    for f in vulns:
        by_sev.setdefault(f["severity"], []).append(f)

    rows = ""
    for f in findings:
        color  = SEVERITY_COLOR.get(f["severity"], "#95a5a6")
        status_badge = (
            f'<span style="background:#e74c3c;color:#fff;padding:2px 8px;border-radius:4px">VULNERABLE</span>'
            if f["status"] == "VULNERABLE" else
            f'<span style="background:#2ecc71;color:#fff;padding:2px 8px;border-radius:4px">SAFE</span>'
        )
        rows += f"""
        <tr>
          <td>{f['test_id']}</td>
          <td>{f['category']}</td>
          <td>{f['name']}</td>
          <td><span style="color:{color};font-weight:bold">{f['severity']}</span></td>
          <td>{status_badge}</td>
          <td style="font-size:12px;color:#666">{f['payload']}</td>
        </tr>"""

    summary_cards = ""
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        count = len(by_sev.get(sev, []))
        color = SEVERITY_COLOR.get(sev, "#95a5a6")
        summary_cards += f"""
        <div style="background:{color}15;border:1px solid {color};border-radius:8px;padding:16px;text-align:center;min-width:100px">
          <div style="font-size:28px;font-weight:bold;color:{color}">{count}</div>
          <div style="font-size:12px;color:#333">{sev}</div>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>LLM Red Team Report — {meta['target']}</title>
  <style>
    body {{ font-family: 'Segoe UI', sans-serif; margin: 0; padding: 32px; background: #f8f9fa; color: #2c3e50; }}
    h1 {{ color: #2c3e50; }} h2 {{ color: #34495e; border-bottom: 2px solid #eee; padding-bottom: 8px; }}
    table {{ width:100%; border-collapse:collapse; background:#fff; border-radius:8px; overflow:hidden; box-shadow:0 1px 4px #0001; }}
    th {{ background:#2c3e50; color:#fff; padding:10px 12px; text-align:left; font-size:13px; }}
    td {{ padding:10px 12px; border-bottom:1px solid #f0f0f0; font-size:13px; vertical-align:top; }}
    tr:hover td {{ background:#fafafa; }}
    .meta {{ background:#fff; border-radius:8px; padding:16px 24px; margin-bottom:24px; box-shadow:0 1px 4px #0001; }}
    .cards {{ display:flex; gap:16px; flex-wrap:wrap; margin-bottom:24px; }}
  </style>
</head>
<body>
  <h1>🔴 LLM Red Team Report</h1>
  <div class="meta">
    <b>Target:</b> {meta['target']} &nbsp;|&nbsp;
    <b>Model:</b> {meta['model']} &nbsp;|&nbsp;
    <b>Date:</b> {meta['timestamp'][:19]} &nbsp;|&nbsp;
    <b>Tester:</b> {meta['tester']} &nbsp;|&nbsp;
    <b>Total Tests:</b> {total} &nbsp;|&nbsp;
    <b>Vulnerabilities:</b> {len(vulns)}
  </div>
  <h2>Summary</h2>
  <div class="cards">{summary_cards}</div>
  <h2>Detailed Findings</h2>
  <table>
    <thead><tr><th>ID</th><th>Category</th><th>Test</th><th>Severity</th><th>Status</th><th>Payload (truncated)</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
  <p style="margin-top:32px;font-size:12px;color:#999">Generated by LLM Red Teaming Framework — github.com/om-awachar/llm-redteam</p>
</body>
</html>"""

    out = Path(output_dir) / f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    out.write_text(html)
    return str(out)
